# Generated by Django 5.1.1 on 2024-09-16 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0003_remove_doctor_available_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='patient/media/uploads')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('relation', models.CharField(max_length=10)),
                ('hight', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=10)),
                ('bloodgroup', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ratting', models.CharField(choices=[('⭐', '1'), ('⭐⭐', '2'), ('⭐⭐⭐', '3'), ('⭐⭐⭐⭐', '4'), ('⭐⭐⭐⭐⭐', '5')], max_length=10)),
                ('docter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
