# Generated by Django 5.1.1 on 2024-09-17 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_remove_doctor_available_time_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NationID',
            new_name='NationalID',
        ),
    ]
